version: '2'

services:
  bot:
    build: 
      context: ./bot
      dockerfile: ./Dockerfile
    networks:
      - my-network
    container_name: telebot_bot
    restart: unless-stopped
    env_file:
      - .env
  
  backend:
    container_name: telebot_backend
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:
      - my-network
    ports:
      - 8000:8000
    env_file:
      - .env
  
  db_cache:
    container_name: telebot_db_cache
    image: redis
    ports:
      - 6379:6379

networks:
  my-network:
    driver: bridge