version: '2'

services:
  bot:
    build: 
      context: ./bot
      dockerfile: ./Dockerfile
    networks:
      - my-network
    container_name: python-bot
    restart: unless-stopped
    env_file:
      - .env
  

  backend:
    container_name: russpass_backend
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:
      - my-network
    ports:
      - 8000:8000
    env_file:
      - .env


networks:
  my-network:
    driver: bridge