version: '2'

services:
  bot:
    build: 
      context: ./bot
      dockerfile: ./Dockerfile
    container_name: python-bot

    restart: unless-stopped
    env_file:
      - .env
  

  backend:
    container_name: server_bot
    build:
      context: ./server
      dockerfile: ./Dockerfile