# Generated by Django 5.1.1 on 2024-09-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShkolnaiaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cold_kitchen', models.IntegerField(null=True)),
                ('warm_kitchen', models.IntegerField(null=True)),
                ('cold_bath', models.IntegerField(null=True)),
                ('warm_bath', models.IntegerField(null=True)),
                ('electric', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Школьная',
                'verbose_name_plural': 'Школьная',
            },
        ),
        migrations.CreateModel(
            name='ZipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cold', models.IntegerField(null=True)),
                ('warm', models.IntegerField(null=True)),
                ('electric', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Зиповская',
                'verbose_name_plural': 'Зиповская',
            },
        ),
    ]
