# Generated by Django 5.1.1 on 2024-09-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shkolnaiamodel',
            name='date_to',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='zipmodel',
            name='date_to',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
